name: hs-rock-paper-scissors
version: 0.1.0.0
github: "sassela/hs-rock-paper-scissors"
license: BSD3
author: "Abby Sassel"
maintainer: "abby.sassel@gmail.com"
copyright: "Abby Sassel"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/sassela/hs-rock-paper-scissors#readme>

dependencies:
  - base >= 4.7 && < 5
  - codeworld-api
  - random
  - text

library:
  source-dirs: src

executables:
  hs-rock-paper-scissors-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-rock-paper-scissors

tests:
  hs-rock-paper-scissors-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hs-rock-paper-scissors
